#:schema node_modules/wrangler/config-schema.json
name = "expense-manager-mini-app"
pages_build_output_dir = "dist"

[vars]
# Add any environment variables here

[compatibility]
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]
